version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: golang:latest
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: